Models/State.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_Morton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}

Controllers/StateController.cs
using Project3_Morton.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project3_Morton.Controllers
{
    public class StateController : Controller
    {
        // GET: State
        /// <summary>
        /// make list of all states that are no deleted and sort
        /// </summary>
        /// <param name="id"></param>
        /// <param name="sortBy"></param>
        /// <param name="isDesc"></param>
        /// <returns></returns>
        public ActionResult All(string id, int sortBy = 0, bool isDesc = false)
        {
            BooksEntities context = new BooksEntities();
            List<State> states = context.States.Where(c => c.IsDeleted == false).ToList();
            switch (sortBy)
            {
                case 1:
                    {
                        if (isDesc)
                            states = states.OrderByDescending(c => c.StateName).ToList();
                        else
                            states = states.OrderBy(c => c.StateName).ToList();
                        break;
                    }
                default:
                    if (isDesc)
                        states = states.OrderByDescending(c => c.StateCode).ToList();
                    else
                        states = states.OrderBy(c => c.StateCode).ToList();
                    break;
            }
            if (!string.IsNullOrWhiteSpace(id))
            {
                id = id.Trim().ToLower();
                states = states.Where(c =>
                         c.StateName.ToLower().Contains(id) ||
                         c.StateCode.ToLower().Contains(id)

                    ).ToList();
            }
            return View(states);
        }

        /// <summary>
        /// update or delete state get
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Upsert(string id)
        {
            BooksEntities context = new BooksEntities();
            State states = context.States.Where(c => c.StateCode == id).FirstOrDefault();

            if (states == null)
            {
                states = new State();
            }
            return View(states);
        }


        /// <summary>
        /// update or add state post
        /// </summary>
        /// <param name="newState"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Upsert(State newState)
        {
            BooksEntities context = new BooksEntities();


            if (context.States.Where(c => c.StateCode == newState.StateCode).Count() > 0)
            {
                var stateToSave = context.States.Where(c => c.StateCode == newState.StateCode).FirstOrDefault();

                stateToSave.StateName = newState.StateName;

            }
            else
            {
                context.States.Add(newState);
            }

            context.SaveChanges();
            return RedirectToAction("All");
        }


        /// <summary>
        /// delete state get
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Delete(string id)
        {
            BooksEntities context = new BooksEntities();
            State state = context.States.Where(c => c.StateCode == id).FirstOrDefault();
            return View(state);
        }


        /// <summary>
        /// delete state post
        /// </summary>
        /// <param name="customer"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(State state)
        {
            BooksEntities context = new BooksEntities();
            try
            {
                if (context.States.Where(c => c.StateCode == state.StateCode).Count() > 0)
                {
                    State stateDelete = context.States.Where(c => c.StateCode == state.StateCode).FirstOrDefault();
                    stateDelete.IsDeleted = true;
                }
                context.SaveChanges();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("All");
        }
    }
}

Views/State/All.cshtml
@model List<Project3_Morton.Models.State>
@{
    ViewBag.Title = "All";
}

<h2>All States</h2>

<a href="/State/Upsert/0">Add New</a>

<div class="row">
    <div class="col-md-6">
        <input id="txtSearch" type="text" class="form-control" placeholder="Search..." />
    </div>
    <div class="col-md-6">
        <input type="button" class="btn btn-info" value="Search" onclick="Sortable.Search()" />

    </div>
</div>

<table class="sortable table table-hover">
    <thead>
        <tr>
            <th onclick="Sortable.Sort(0)">State Code</th>
            <th onclick="Sortable.Sort(1)">State Name</th>
            
            <th>Actions</th>

        </tr>
    </thead>

    <tbody>
        @foreach (var states in Model)
        {
            <tr>
                <td>@states.StateCode</td>
                <td>@states.StateName</td>
                

                <td>
                    <a href="/state/Upsert/@states.StateCode">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/State/Delete.cshtml
@model Project3_Morton.Models.State
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@using (Html.BeginForm("Delete", "State", FormMethod.Post))
{
    <h3>Are you sure you want to delete this state?</h3>
    @Html.HiddenFor(c => c.StateCode, new { @class = "form-control", placeholder = "State Code" })
    @Html.HiddenFor(c => c.StateName, new { @class = "form-control", placeholder = "State Name" })

    <input type="submit" value="Submit" class="btn btn-info" />
    <input type="button" value="Cancel" class="btn btn-danger" onclick="window.location.href = '/State/All'" />
}

Views/State/Upsert.cshtml
@model Project3_Morton.Models.State
@{
    ViewBag.Title = "Upsert";
}

<h2>Upsert a State</h2>

@using (Html.BeginForm("Upsert", "State", FormMethod.Post))
{
    @Html.TextBoxFor(c => c.StateCode, new { @class = "form-control", placeholder = "State Code" })
    @Html.TextBoxFor(c => c.StateName, new { @class = "form-control", placeholder = "State Name" })

    <input type="submit" value="submit" class="btn btn-info" />
    <input type="button" value="Delete" class="btn btn-danger" onclick="window.location.href = ('/State/Delete/@Model.StateCode')" />
}