Models/InvoiceLineItem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_Morton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineItem
    {
        public int InvoiceID { get; set; }
        public string ProductCode { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public decimal ItemTotal { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}

Controllers/InvoiceLineItemController.cs
using Project3_Morton.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project3_Morton.Controllers
{
    public class InvoiceLineItemController : Controller
    {
        // GET: InvoiceLineItem'
        /// <summary>
        /// get all invoice line items and sort
        /// </summary>
        /// <param name="id"></param>
        /// <param name="sortBy"></param>
        /// <param name="isDesc"></param>
        /// <returns></returns>
        public ActionResult All(string id, int sortBy = 0, bool isDesc = false)
        {
            BooksEntities context = new BooksEntities();
            List<InvoiceLineItem> invoiceLineItems;
           

            switch (sortBy)
            {
                case 1:
                    {
                        if (isDesc)
                            invoiceLineItems = context.InvoiceLineItems.OrderByDescending(c => c.ProductCode).ToList();
                        else
                            invoiceLineItems = context.InvoiceLineItems.OrderBy(c => c.ProductCode).ToList();
                        break;
                    }
                case 2:
                    {
                        if (isDesc)
                            invoiceLineItems = context.InvoiceLineItems.OrderByDescending(c => c.Quantity).ToList();
                        else
                            invoiceLineItems = context.InvoiceLineItems.OrderBy(c => c.Quantity).ToList();
                        break;
                    }
                case 3:
                    {
                        if (isDesc)
                            invoiceLineItems = context.InvoiceLineItems.OrderByDescending(c => c.ItemTotal).ToList();
                        else
                            invoiceLineItems = context.InvoiceLineItems.OrderBy(c => c.ItemTotal).ToList();
                        break;
                    }
                case 4:
                    {
                        if (isDesc)
                            invoiceLineItems = context.InvoiceLineItems.OrderByDescending(c => c.UnitPrice).ToList();
                        else
                            invoiceLineItems = context.InvoiceLineItems.OrderBy(c => c.UnitPrice).ToList();
                        break;
                    }         
                case 0:
                default:
                    if (isDesc)
                        invoiceLineItems = context.InvoiceLineItems.OrderByDescending(c => c.InvoiceID).ToList();
                    else
                        invoiceLineItems = context.InvoiceLineItems.OrderBy(c => c.InvoiceID).ToList();
                    break;
            }
            if (!string.IsNullOrWhiteSpace(id))
            {
                id = id.Trim().ToLower();
                invoiceLineItems = invoiceLineItems.Where(c =>
                         c.ProductCode.ToLower().Contains(id) 
                    ).ToList();
            }
            return View(invoiceLineItems);
        }

        /// <summary>
        /// add or delete lineitem get
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Upsert(int id)
        {
            BooksEntities context = new BooksEntities();
            InvoiceLineItem invoiceLineItems = context.InvoiceLineItems.Where(i => i.InvoiceID == id).FirstOrDefault();
            List<Product> products = context.Products.ToList();

            UpsertItemsModel viewModel = new UpsertItemsModel()
            {
                InvoiceLineItem = invoiceLineItems,
                Products = products
            };

            return View(viewModel);
        }

        /// <summary>
        /// add or delete line items post
        /// </summary>
        /// <param name="model"></param>
        /// <param name="productcode"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Upsert(UpsertItemsModel model, string productcode)
        {
            InvoiceLineItem newInvoiceLineItem = model.InvoiceLineItem;
            newInvoiceLineItem.ProductCode = productcode;
            BooksEntities context = new BooksEntities();


            if (context.InvoiceLineItems.Where(i => i.InvoiceID == newInvoiceLineItem.InvoiceID).Count() > 0)
            {
                var invoiceLineItemToSave = context.InvoiceLineItems.Where(i => i.InvoiceID == newInvoiceLineItem.InvoiceID).FirstOrDefault();

                invoiceLineItemToSave.ItemTotal = newInvoiceLineItem.ItemTotal;
                invoiceLineItemToSave.ProductCode = newInvoiceLineItem.ProductCode;
                invoiceLineItemToSave.Quantity = newInvoiceLineItem.Quantity;
                invoiceLineItemToSave.UnitPrice = newInvoiceLineItem.UnitPrice;
            }
            else
            {
                context.InvoiceLineItems.Add(newInvoiceLineItem);
            }

            context.SaveChanges();
            return RedirectToAction("All");
        }
    }
}

Views/InvoiceLineItem/All.cshtml
@model List<Project3_Morton.Models.InvoiceLineItem>
@{
    ViewBag.Title = "All";
}

<h2>All Invoice Line Items</h2>

<a href="/InvoiceLineItem/Upsert/0">Add New</a>

<div class="row">
    <div class="col-md-6">
        <input id="txtSearch" type="text" class="form-control" placeholder="Search..." />
    </div>
    <div class="col-md-6">
        <input type="button" class="btn btn-info" value="Search" onclick="Sortable.Search()" />

    </div>
</div>

<table class="sortable table table-hover">
    <thead>
        <tr>
            <th onclick="Sortable.Sort(0)">Invoice ID</th>
            <th onclick="Sortable.Sort(1)">Product Code</th>
            <th onclick="Sortable.Sort(2)">Quantity</th>
            <th onclick="Sortable.Sort(3)">Unit Price</th>
            <th onclick="Sortable.Sort(4)">Item Total</th>
            <th>Actions</th>

        </tr>
    </thead>

    <tbody>
        @foreach (var InvoiceLineItem in Model)
        {
            <tr>
                <td>@InvoiceLineItem.InvoiceID</td>
                <td>@InvoiceLineItem.ProductCode</td>
                <td>@InvoiceLineItem.Quantity</td>
                <td>@InvoiceLineItem.UnitPrice</td>
                <td>@InvoiceLineItem.ItemTotal</td>
                <td>
                    <a href="/InvoiceLineItem/Upsert/@InvoiceLineItem.InvoiceID">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/InvoiceLineItem/Upsert.cshtml
@model Project3_Morton.Models.UpsertItemsModel
@{
    ViewBag.Title = "Upsert";
}

<h2>Upsert a Item</h2>

@using (Html.BeginForm("Upsert", "InvoiceLineItem", FormMethod.Post))
{
    @Html.TextBoxFor(gm => gm.InvoiceLineItem.InvoiceID, new { @class = "form-control", placeholder = "Invoice ID" })
    @Html.TextBoxFor(gm => gm.InvoiceLineItem.ProductCode, new { @class = "form-control", placeholder = "Product Code" })
    @Html.TextBoxFor(gm => gm.InvoiceLineItem.ItemTotal, new { @class = "form-control", placeholder = "Item Total" })
    @Html.TextBoxFor(gm => gm.InvoiceLineItem.Quantity, new { @class = "form-control", placeholder = "Quantity" })
    @Html.TextBoxFor(gm => gm.InvoiceLineItem.UnitPrice, new { @class = "form-control", placeholder = "Unit Price" })

    <input list = "State" name = "productcode" >

    <datalist id="State">
        @foreach (var id in Model.Products)
        {
            <option value="@id.ProductCode"></option>
        }
    </datalist>


    <input type="submit" value="submit" class="btn btn-info" />
}