Models/OrderOption.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_Morton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderOption
    {
        public decimal SalesTaxRate { get; set; }
        public decimal FirstBookShipCharge { get; set; }
        public decimal AdditionalBookShipCharge { get; set; }
        public bool IsDeleted { get; set; }
        public int Id { get; set; }
    }
}

Controllers/OrderOptionController.cs
using Project3_Morton.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project3_Morton.Controllers
{
    public class OrderOptionController : Controller
    {
        // GET: OrderOption
        /// <summary>
        /// get list of all orderoptions that are not deleted and sort
        /// </summary>
        /// <param name="id"></param>
        /// <param name="sortBy"></param>
        /// <param name="isDesc"></param>
        /// <returns></returns>
        public ActionResult All(string id, int sortBy = 0, bool isDesc = false)
        {
            BooksEntities context = new BooksEntities();
            List<OrderOption> orders = context.OrderOptions.Where(c => c.IsDeleted == false).ToList();
            switch (sortBy)
            {
                case 1:
                    {
                        if (isDesc)
                            orders = orders.OrderByDescending(c => c.SalesTaxRate).ToList();
                        else
                            orders = orders.OrderBy(c => c.SalesTaxRate).ToList();
                        break;
                    }
                case 2:
                    {
                        if (isDesc)
                            orders = orders.OrderByDescending(c => c.FirstBookShipCharge).ToList();
                        else
                            orders = orders.OrderBy(c => c.FirstBookShipCharge).ToList();
                        break;
                    }
                case 3:
                    {
                        if (isDesc)
                            orders =orders.OrderByDescending(c => c.FirstBookShipCharge).ToList();
                        else
                            orders = orders.OrderBy(c => c.FirstBookShipCharge).ToList();
                        break;
                    }
                case 0:
                default:
                    if (isDesc)
                        orders = orders.OrderByDescending(c => c.Id).ToList();
                    else
                        orders = orders.OrderBy(c => c.Id).ToList();
                    break;
            }
            return View(orders);
        }

        /// <summary>
        /// add or update orderoption get
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Upsert(int id)
        {
            BooksEntities context = new BooksEntities();
            OrderOption orderOption = context.OrderOptions.Where(c => c.Id == id).FirstOrDefault();

            if (orderOption == null)
            {
                orderOption = new OrderOption();
            }
            return View(orderOption);
        }

        /// <summary>
        /// add or delete orderoption post
        /// </summary>
        /// <param name="neworderOption"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Upsert(OrderOption neworderOption)
        {
            BooksEntities context = new BooksEntities();


            if (context.OrderOptions.Where(c => c.Id == neworderOption.Id).Count() > 0)
            {
                var customerToSave = context.OrderOptions.Where(c => c.Id == neworderOption.Id).FirstOrDefault();

                customerToSave.AdditionalBookShipCharge = neworderOption.AdditionalBookShipCharge;
                customerToSave.SalesTaxRate = neworderOption.SalesTaxRate;
                customerToSave.FirstBookShipCharge = neworderOption.FirstBookShipCharge;
            }
            else
            {
                context.OrderOptions.Add(neworderOption);
            }

            context.SaveChanges();
            return RedirectToAction("All");
        }
        /// <summary>
        /// delete orderoptions post
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Delete(int id)
        {
            BooksEntities context = new BooksEntities();
            OrderOption order = context.OrderOptions.Where(c => c.Id == id).FirstOrDefault();
            return View(order);
        }


        /// <summary>
        /// delete orderoptions get
        /// </summary>
        /// <param name="order"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(OrderOption order)
        {
            BooksEntities context = new BooksEntities();
            try
            {
                if (context.OrderOptions.Where(c => c.Id == order.Id).Count() > 0)
                {
                    OrderOption orderDelete = context.OrderOptions.Where(c => c.Id == order.Id).FirstOrDefault();
                    orderDelete.IsDeleted = true;
                }
                context.SaveChanges();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("All");
        }

    }
}

Views/OrderOption/All.cshtml
@model List<Project3_Morton.Models.OrderOption>
@{
    ViewBag.Title = "All";
}

<h2>All Orders</h2>

<a href="/OrderOption/Upsert/0">Add New</a>

<div class="row">
    <div class="col-md-6">
        <input id="txtSearch" type="text" class="form-control" placeholder="Search..." />
    </div>
    <div class="col-md-6">
        <input type="button" class="btn btn-info" value="Search" onclick="Sortable.Search()" />

    </div>
</div>

<table class="sortable table table-hover">
    <thead>
        <tr>
            <th onclick="Sortable.Sort(0)">ID</th>
            <th onclick="Sortable.Sort(1)">AdditionalBookShipCharge</th>
            <th onclick="Sortable.Sort(2)">SalesTax Rate</th>
            <th onclick="Sortable.Sort(3)">First Book Ship Charge</th>
            <th>Actions</th>

        </tr>
    </thead>

    <tbody>
        @foreach (var orderOption in Model)
        {
            <tr>
                <td>@orderOption.Id</td>
                <td>@orderOption.AdditionalBookShipCharge</td>
                <td>@orderOption.SalesTaxRate</td>
                <td>@orderOption.FirstBookShipCharge</td>
             
                <td>
                    <a href="/OrderOption/Upsert/@orderOption.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/OrderOption/Delete.cshtml
@model Project3_Morton.Models.OrderOption
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@using (Html.BeginForm("Delete", "OrderOption", FormMethod.Post))
{
    <h3>Are you sure you want to delete this customer?</h3>
    @Html.HiddenFor(c => c.Id)
    @Html.HiddenFor(c => c.AdditionalBookShipCharge, new { @class = "form-control", placeholder = "AdditionalBook ShipCharge" })
    @Html.HiddenFor(c => c.FirstBookShipCharge, new { @class = "form-control", placeholder = "FirstBookShipCharge" })
    @Html.HiddenFor(c => c.SalesTaxRate, new { @class = "form-control", placeholder = "SalesTaxRate" })

    <input type="submit" value="Submit" class="btn btn-info" />
    <input type="button" value="Cancel" class="btn btn-danger" onclick="window.location.href = '/OrderOption/All'" />
}

Views/OrderOption/Upsert.cshtml
@model Project3_Morton.Models.OrderOption
@{
    ViewBag.Title = "Upsert";
}

<h2>Upsert a Order Option</h2>

@using (Html.BeginForm("Upsert", "OrderOption", FormMethod.Post))
{
    @Html.HiddenFor(c => c.Id)
    @Html.TextBoxFor(c => c.AdditionalBookShipCharge, new { @class = "form-control", placeholder = "AdditionalBook ShipCharge" })
    @Html.TextBoxFor(c => c.FirstBookShipCharge, new { @class = "form-control", placeholder = "FirstBookShipCharge" })
    @Html.TextBoxFor(c => c.SalesTaxRate, new { @class = "form-control", placeholder = "SalesTaxRate" })

    <input type="submit" value="submit" class="btn btn-info" />
    <input type="button" value="Delete" class="btn btn-danger" onclick="window.location.href = ('/OrderOption/Delete/@Model.Id')" />
}